data_dir: ../../../msd-splits/dataset
msu_dir: ../../../MSU/dataset
framework: contrastive
arch: transformer
workers: 12
epochs: 200
warmup_epochs: 10
start_epoch: 0
batch_size: 64
world_size: 1
lr: 0.0001
min_lr: 1.0e-09
seed: null
gpu: 1
duration: 9.91
sr: 16000
num_chunks: 8
mel_dim: 128
n_fft: 1024
win_length: 1024
frontend: cnn
mix_type: cf
audio_rep: mel
text_type: bert
text_rep: stochastic
cos: true
attention_nlayers: 4
attention_ndim: 256
text_backbone: bert-base-uncased
probe_type: zs
eval_dataset: mtg_top50tags
